name            = "MarkersPlus";
author          = "Pek";
picture         = "\markersplus\data\logo.paa";
logo            = "\markersplus\data\logo.paa";
logoOver        = "\markersplus\data\logoOver.paa";
logoSmall       = "\markersplus\data\logo.paa";
tooltip         = "MarkersPlus";
tooltipOwned    = "MarkersPlus";
actionName      = "User guide";
action          = "https://steamcommunity.com/sharedfiles/filedetails/?id=3365010538";
overview        = "Tactical map symbols, contact reports and saved plans for Arma 3. Requires CBA_A3 and ACE3.";
dlcColor[]      = {1,0.7294,0.1490,1};
hideName        = 0;
hidePicture     = 0;
